- name: Patch OS playbook
  hosts: all
  tasks:
#    - name: Check environment
#      command:  hostname|cut -d- -f2
#      register: environment_name
    - name: Run yum list
      yum:
        list: ansible
      register: result  
      when:
        (environment_name == "infp" and ansible_distribution == "OracleLinux")
    - name: take out of load balancer pool
      local_action: copy content={{ result }} dest=/tmp/ansible_file.txt
    
    - name: Print result
      debug:
        msg: "Result is {{ result }}"
