- name: Patch OS playbook
  hosts: all
  tasks:
#    - name: Check environment
#      command:  hostname|cut -d- -f2
#      register: environment_name
    - command: "ls /etc/ansible/"
      register: dir_out
#    - name: Run yum list
#      yum:
#        list: ansible
#      register: result  
#      when:
#        (environment_name == "infp" and ansible_distribution == "OracleLinux")
    - name: Print result to file
      local_action: copy content={{dir_out}} dest=/tmp/ansible_file.txt
    
#    - name: Print result
#      debug:
#        msg: "Result is {{ result }}"
