- name: Patch OS playbook
  hosts: all
  tasks:
#    - name: Check environment
#      command:  hostname|cut -d- -f2
#      register: environment_name
    - name: Patching Red Hat Enterprise Linux
      yum:
        list: ansible
      when:
        - environment_name == "infp"
