- name: Patch OS playbook
  hosts: all
  tasks:
#    - name: Check environment
#      command:  hostname|cut -d- -f2
#      register: environment_name
    - name: Run yum list
      yum:
        list: ansible
      register: result  
      when:
        (environment_name == "infp" and ansible_distribution == "OracleLinux")
       
    - name: Print dev result
      debug:
        msg: "Result is {{ result }}"
